name: Twitter_Bot
on:
  push:
    branches: 
      - main
  schedule:
    # 定期実行する時間・・・①
    - cron: '* */6 * * *'

jobs:
  build:
    # Ubuntuの最新版環境内で処理を実行することを指定
    runs-on: ubuntu-latest

    # 実行する処理＆コマンド指定
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10.2
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.2
      - name: Install dependencies
        run:
          # pip更新
          python -m pip install --upgrade pip
          pip install python-dotenv
          pip install tweepy
          pip install numpy

      - name: Run script
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
        run:
          # 定期実行するファイルを指定。・・・③
          python Twitter_Bot.py
